services:
  - type: web
    name: mhenga-crop-bot
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 3"
    envVars:
      - key: AGROMONITORING_API_KEY
        value: ""
      - key: ROBOFLOW_API_KEY
        value: ""
      - key: ROBOFLOW_MODEL_ID
        value: ""
      - key: ROBOFLOW_MODEL_VERSION
        value: ""
      - key: JWT_SECRET_KEY
        value: ""
      - key: MAIL_SERVER
        value: ""
      - key: MAIL_PORT
        value: ""
      - key: MAIL_USERNAME
        value: ""
      - key: MAIL_PASSWORD
        value: ""
      - key: MAIL_SENDER_NAME
        value: ""
      - key: MAIL_SENDER_EMAIL
        value: ""
